# Generated by Django 2.0.6 on 2019-06-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emplist_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='headpic',
            field=models.ImageField(default='a', upload_to='pics'),
        ),
    ]
