# Generated by Django 2.0.6 on 2019-06-29 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emplist_app', '0002_employee_headpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.SmallIntegerField(default=1),
        ),
    ]
